baseurl = "https://chs.us/"
title = "chs.us"
languageCode = "en-us"
paginate = "15" # Number of posts per page
theme = "hugo-octopress"
#disqusShortname = "chsus" # Enable Disqus comments by entering your Disqus shortname
#googleAnalytics = "UA-92888611-1" # Enable Google Analytics by entering your tracking id

[params.author.name] # Used in authorbox
  name = "Carl Sampson"
  bio = "I am an application security guy living in Indiana. I also started and lead the OWASP Indianapolis Chapter."
  avatar = "images/chs_avatar.jpg"

[Params]
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "A site about security, development, or anything that Carl Sampson finds generally interesting.  Carl is primarily interested in web application security, OWASP, programming languages, and automation." # Site description. Used in meta description
  copyright = "Carl Sampson" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  #customCSS = ["css/custom.css"] # Include custom CSS files
  #customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "images/chs.jpg" # Logo image. Path relative to "static"
  title = "chs.us" # Logo title, otherwise will use site title
  #subtitle = "Just another site" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  #widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  #widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  twitter = "chs"
  #instagram = "username"
  linkedin = "carlsampson"
  telegram = "sampsonc"
  github = "sampsonc"
  #gitlab = "username"
  #bitbucket = "username"
  email = "chs@chs.us"

# Custom social links
#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://youtube.com/user/username"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

#[[Params.widgets.social.custom]]
#  title = "My Home Page"
#  url = "http://example.com"

  #[[menu.main]]
  #  name = "Meet"
  #  pre = "<i class='fa fa-road'></i>"
  #  url = "https://calendly.com/sampsonc"
  #  weight = -102

  [[menu.main]]
  #  name = "My Medium Profile"
  #  pre = "<i class='fa fa-road'></i>"
  #  url = "https://medium.com/@sampsonc"
  #  weight = 200

  [[menu.main]]
    name = " "
    pre = "<i class='fa fa-road'></i>"
    url = "http://canarytokens.com/articles/traffic/static/48ihq6348es80aygmnrrbj97e/index.html"
    weight = 2000

  [[menu.main]]
    name = "appsec.fyi"
    pre = "<i class='fa fa-road'></i>"
    url = "https://appsec.fyi/"
    weight = -100

#  [[menu.main]]
#    name = "RSS Feed"
#    pre = "<i class='fa fa-road'></i>"
#    url = "//index.xml"
#    weight = 1001

  [[menu.main]]
    name = "links"
    pre = "<i class='fa fa-road'></i>"
    url = "//links/index.html"
    weight = 1000

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe=true

  filename = 'sitemap.xml'
  priority = 0.5
