name: Build and Deploy
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 * * * *'
 
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
 
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
 
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master
 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.92.2'
 
    - name: Build
      run: hugo --minify

    - name: ls directory
      run: ls -al /home/runner/work/chs.us.v3/chs.us.v3/public
 
    - name: Copy to webserver
      run: rsync -avz --delete public/ chs@chs.us:chs.us/
